### PR TITLE
Adapt kong-patter branch to VP structure

### PR DESCRIPTION
**Pull request by ruromero**
* Auto create ArgoCD secrets
* Bookinfo project
* Control Plane and Data Plane project
* Control Plane with Postgresql chart (from OCP template)

**Note** Keycloak , Grafana and Prometheus not yet integrated

Signed-off-by: ruromero <rromerom@redhat.com>

### CODE REVIEW

**Comment by mpaulgreen** [comment]
Hi Ruben, I started having the cursory look at your PR, it seems like you are missing keycloak, prometheus and grafana deployment. Refer- [Supporting infra](https://github.com/hybrid-cloud-patterns/kong-gateway/tree/kong-pattern/gateway/prereqs/overlays/dp)
Also you are missing annotations for cp and dp - Refer - [dp](https://github.com/hybrid-cloud-patterns/kong-gateway/blob/kong-pattern/gateway/prereqs/overlays/dp/patch.yaml) and [cp](https://github.com/hybrid-cloud-patterns/kong-gateway/blob/kong-pattern/gateway/prereqs/overlays/cp/patch.yaml)
This is probably the reason you are not see all the application get un deployed correctly
sync waves are integral to design of these apps.

I also just noticed that all UTs are not passing.

**Comment by mpaulgreen** [comment]
Hi Ruben, why did you change to deployment config for postgres. I did so that we can port these on any k8s cluster in future. I know there will be still more changes but we will have one less item

**Comment by ruromero** [comment]
> Hi Ruben, why did you change to deployment config for postgres. I did so that we can port these on any k8s cluster in future. I know there will be still more changes but we will have one less item

The main reason is that the Postgresql image deployed with the chart requires too many permissions and needs to be tweaked to be deployed on OpenShift. The one used in this PR works on any k8s cluster + OpenShift. This chart is very easy to maintain. I can extract it to a different repo if you prefer but I don't think it'd be necessary.

**Comment by ruromero** [comment]
> Hi Ruben, I started having the cursory look at your PR, it seems like you are missing keycloak, prometheus and grafana deployment. Refer- [Supporting infra](https://github.com/hybrid-cloud-patterns/kong-gateway/tree/kong-pattern/gateway/prereqs/overlays/dp) Also you are missing annotations for cp and dp - Refer - [dp](https://github.com/hybrid-cloud-patterns/kong-gateway/blob/kong-pattern/gateway/prereqs/overlays/dp/patch.yaml) and [cp](https://github.com/hybrid-cloud-patterns/kong-gateway/blob/kong-pattern/gateway/prereqs/overlays/cp/patch.yaml) This is probably the reason you are not see all the application get un deployed correctly sync waves are integral to design of these apps.

The problem noted in the README is not related to the undeploy but to the deploy of the main argo app under openshift-gitops so annotations/waves are not the issue here. I can continue investigating but so far deployment has proved to happen in the right order.

> I also just noticed that all UTs are not passing.

The error is caused by the Kong Helm Chart: `Deployment release-name-kong is invalid: For field spec.template.spec.containers.0: Additional property terminationGracePeriodSeconds is not allowed`

**Comment by mpaulgreen** [comment]
The kind: DeploymentConfig is specific to OpenShift. I dont think it will work with other distribution of OpenShift. Also were you able to add the monitoring and keycloak templates in the code yet?

**Comment by mpaulgreen** [comment]
The apps are not synced beyond kong-cp. Using the repo that is existing in kong-pattern branch, we could reuse the apps already developed and working.

**Comment by ruromero** [comment]
> The apps are not synced beyond kong-cp. Using the repo that is existing in kong-pattern branch, we could reuse the apps already developed and working.

Including the ArgoCD cluster creation?

**Comment by mpaulgreen** [comment]
The clusters are created. It is just the apps that are not synced.

**Comment by ruromero** [comment]
The point is to use the apps the way they're defined and deployed by the VP framework. And if the framework is lacking some capabilities, try to fix/enhance it

**Comment by mpaulgreen** [comment]
The way it has been done here is fine using the VP framework's app schematics, as long as it works while deploying. One of the discussion I had with the validated framework team on chat on Friday was to separate the product and pattern. Continue with your fix. I will check to separate the pattern from the product.

**Comment by ruromero** [comment]
@mpaulgreen after the latest changes all the applications are deployed successfully

**Comment by ruromero** [comment]
I think it's good to merge and after this I will continue with the missing pieces (Keycloak, Prometheus, Grafana)

**Comment by mpaulgreen** [comment]
Actually, I am using my cluster for other purpose, but I will try to test it in couple of days. You go ahead with rest of the pieces. May be you can prioritize the secret creation.

**Comment by mpaulgreen** [comment]
ok, @ruromero The good news is everything got deployed. However, for kong in data plane `CLUSTER_URL` and `CLUSTER_TELEMETRY_URL` is never patched. Refer - https://github.com/hybrid-cloud-patterns/kong-gateway/blob/kong-gateway/gateway/dataplane/values.yaml. The Ingress is not working - Refer the section Validate Ingress in https://github.com/hybrid-cloud-patterns/kong-gateway/tree/kong-pattern/README.md

**Comment by ruromero** [comment]
I'd rather have this PR merged and incrementally add new features. This is already too complex

**Comment by ruromero** [comment]
@mpaulgreen the problem with the sync was caused by the `ignoreDifferences` not properly defined. It should be fine now

**Comment by mpaulgreen** [comment]
@ruromero Why did you change all the images from quay.io/mpaulgreen/argo-helper:1.0 to cmwylie19/kube-argo-base? Was there an issue with the earlier image. Also, there are a lot of commented code and sync waves still in the code. Can you remove the commented code. I dont think you are using the sync wave.

**Comment by mpaulgreen** [comment]
This branch is considered to be merged (after code review) as it covers the basic functionality. There are pending items such as auth, ,metrics and secret management that will be handled in subsequent PR.

**Comment by ruromero** [comment]
I have created the ecosystem-appeng repos for the images and did the clean up of unused resources and commented out lines

**Comment by mpaulgreen** [comment]
Some of UTs are failing

**Pull request merged**
